### ISSUE TITLE
Error When Execute

### ISSUE THREAD

**Issue by crashangelbr** [KevCui/translate-cli#2]
Hi, I receive this error when execute ./translate.js -t de 'Hold my beer'

`/home/development/Projects/translate-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:707
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/development/Projects/translate-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Target.js:19:19)
`

**Comment by KevCui** [comment]
There were some changes on Google Translate web page. The selectors class names were removed and replaced by new class names which are obfuscated. So the missing selectors in the script are causing execution timeout.

I updated the code to use another way to fetch translation. Please check the latest commit to see if it works for you or not. Thanks!
